# Generated by Django 3.0.6 on 2020-05-21 02:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='お題名')),
                ('major_class', models.CharField(max_length=255, verbose_name='大分類')),
                ('medium_class', models.CharField(max_length=255, verbose_name='中分類')),
                ('choice1', models.TextField(max_length=255, verbose_name='選択肢1')),
                ('choice2', models.TextField(max_length=255, verbose_name='選択肢2')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_num', models.IntegerField(verbose_name='選択肢番号')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='which_person_themes.Theme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
