# Generated by Django 3.0.6 on 2020-05-21 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('which_person_themes', '0002_auto_20200521_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255, verbose_name='ユーザ名')),
                ('choice_num', models.IntegerField(verbose_name='選択肢番号')),
                ('comment', models.CharField(max_length=512, verbose_name='コメント')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='which_person_themes.Theme')),
            ],
        ),
    ]
